name: neo4j_build
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7
  - neo4j-python-driver=4.1
  - pandas
  - environs
  - loguru
  - scipy
  - pandas-profiling
  - pytest
  - pydantic
  - pyyaml
  - pip
  - pip:
    - snakemake>=5.27
    - wget
    - biomart
