name: mouse_knockout
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7
  - pip
  - pandas
  - requests
  - tqdm
  - loguru
  - black
  - jupyterlab=2.2
  - nodejs
  - pip:
    - nb_black
