nodes:
  variant-opengwas:
    name: Variant
    files: 
      1: opengwas/opengwas-tophits-2021-05-04.csv
    script: nodes.variant.opengwas
    source: OpenGWAS-2021-05-04

  gwas-opengwas:
    name: Gwas
    files: 
      1: opengwas/opengwas-metadata-2021-05-04.csv
    script: nodes.gwas.opengwas
    source: OpenGWAS-2021-05-04

  gene-biomart:
    name: Gene
    files:
      1 : biomart/gene-data.txt-2020-10-13.gz
    script: nodes.gene.biomart
    source: BioMart-grch37

  protein-biomart:
    name: Protein
    files:
      1 : biomart/protein-only-2020-10-13.txt
    script: nodes.protein.biomart
    source: BioMart-grch37

  pathway-reactome:
    name: Pathway
    files:
      1: reactome/ReactomePathways_human_2020-10-13.csv
    script: nodes.pathway.reactome
    source: Reactome-2020-10-13

  protein-reactome:
    name: Protein
    files:
      1: reactome/UniProt2Reactome_All_Levels_human_2021-05-04.csv
    script: nodes.protein.reactome
    source: Reactome-2021-05-04 

  drug-ot:
    name: Drug
    files:
      1: opentargets/open_targets_2021-05-13.csv
    script: nodes.drug.opentargets
    source: Opentargets-21.04

  variant-xqtl:
    name: Variant
    files: 
      1: xqtl-processed/xqtl_single_snp.csv
    script: nodes.variant.xqtl
    source: xQTL

  variant-mr-eve:
    name: Variant
    files: 
      1: mr-eve/21_03_10/variants.csv.gz
    script: nodes.variant.mr-eve
    source: MR-EvE-2021-03-10

  disease-mondo:
    name: Disease
    files:
      1: mondo/Mondo-2021-05-04.json
    script: nodes.disease.mondo
    source: Mondo-2021-05-04
  
  lit-triple-semmed:
    name: LiteratureTriple
    files:
      1: semmeddb/semmedVER43_2021_R_PREDICATION_filter.csv.gz
    script: nodes.literature_triple.semmed
    source: SemMedDB_VER43_2021_R

  lit-term-semmed:
    name: LiteratureTerm
    files:
      1: semmeddb/semmedVER43_2021_R_PREDICATION_filter.csv.gz
    script: nodes.literature_term.semmed
    source: SemMedDB_VER43_2021_R

  lit-semmed:
    name: Literature
    files:
      1: semmeddb/semmedVER43_2021_R_PREDICATION_filter.csv.gz
      2: semmeddb/semmedVER43_2021_R_CITATIONS.csv.gz
    script: nodes.literature.semmed
    source: SemMedDB_VER43_2021_R
  
  drug-cpic:
    name: Drug
    files:
      1: CPIC/cpicPairs-2021-05-04.csv
    script: nodes.drug.cpic
    source: CPIC-2021-05-04

  tissue-gtex:
    name: Tissue
    files:
      1: gtex/GTEx_Analysis_2017-06-05_v8_RNASeQCv1.1.9_gene_median_tpm.gct.gz
    script: nodes.tissue.gtex
    source: GTEx-2016-01-15_v7_RNASeQCv1.1.8

  protein-string:
    name: Protein
    files:
      1: string-db/9606.protein.links.v11.0.txt.gz
      2: string-db/human.uniprot_2_string.2018.tsv.gz
    script: nodes.protein.string
    source: STRING-v11

  gene-druggable:
    name: Gene
    files:
      1: druggable_genes/druggable_genes.txt
    script: nodes.gene.druggable
    source: Finan_et_al

  ontology-efo:
    name: Efo
    files:
      1: EFO/efo_nodes_2021-05-24.csv
    script: nodes.efo.efo
    source: 2021-04-20 EFO 3.29.1
  
  literature-semrep-biorxiv:
    name: Literature
    files:
      1: semrep/biorxiv_data.csv.gz
      2: semrep/biorxiv_2021-05-05_semrep_filter.csv.gz
    script: nodes.literature.semrep-biorxiv
    source: bioRxiv-2021-05-04

  literature-semrep-medrxiv:
    name: Literature
    files:
      1: semrep/medrxiv_data.csv.gz
      2: semrep/medrxiv_2021-05-05_semrep_filter.csv.gz
    script: nodes.literature.semrep-medrxiv
    source: medRxiv-2021-05-04   

  literature-triple-semrep-biorxiv:
    name: LiteratureTriple
    files:
      1: semrep/biorxiv_2021-05-05_semrep_filter.csv.gz
    script: nodes.literature_triple.semrep-biorxiv
    source: bioRxiv-2021-05-04

  literature-triple-semrep-medrxiv:
    name: LiteratureTriple
    files:
      1: semrep/medrxiv_2021-05-05_semrep_filter.csv.gz
    script: nodes.literature_triple.semrep-medrxiv
    source: medRxiv-2021-05-04

  literature-term-semrep-biorxiv:
    name: LiteratureTerm
    files:
      1: semrep/biorxiv_2021-05-05_semrep_filter.csv.gz
    script: nodes.literature_term.semrep-biorxiv
    source: bioRxiv-2021-05-04

  literature-term-semrep-medrxiv:
    name: LiteratureTerm
    files:
      1: semrep/medrxiv_2021-05-05_semrep_filter.csv.gz
    script: nodes.literature_term.semrep-medrxiv
    source: medRxiv-2021-05-04  
    
rels:
  opengwas-gwas-variant:
    name: OPENGWAS_TOPHITS
    files:
      1: opengwas/opengwas-tophits-2021-05-04.csv
    script: rels.opengwas_tophits
    source: OpenGWAS-2021-05-04
  
  biomart-gene-protein:
    name: GENE_TO_PROTEIN 
    files:
      1: biomart/protein-data-sp-2020-10-13.txt.gz
    script: rels.gene_to_protein
    source: BioMart-grch37

  vep-variant-gene:
    name: VARIANT_TO_GENE
    files:
      1: vep/vep-2021-05-06.txt
    script: rels.variant_to_gene
    source: Ensembl-VEP-v37

  reactome-protein-pathway:
    name: PROTEIN_IN_PATHWAY
    files:
      1: reactome/UniProt2Reactome_All_Levels_human_2021-05-04.csv
    script: rels.reactome_protein_pathway
    source: Reactome-2021-05-04

  reactome-pathway-pathway:
    name: PATHWAY_CHILD_OF
    files:
      1: reactome/ReactomePathwaysRelation_human_2021-05-04.csv
    script: rels.reactome_pathway_pathway
    source: Reactome-2021-05-04

  ot-drug-target:
    name: OPENTARGETS_DRUG_TO_TARGET
    files:
      1: opentargets/open_targets_2021-05-13.csv
    script: rels.opentargets_drug_target
    source: Opentargets-21.04

  obs-cor:
    name: OBS_COR
    files:
      1: ukb_phenotype_correlation_ben/ukb_pheno_cor_0.1_lower.tsv.gz
    script: rels.obs_cor
    source: MRC-IEU UK Biobank - https://www.ukbiobank.ac.uk/tag/15825/

  mr-eve-mr:
    name: MR_EVE_MR
    files:
      1: mr-eve/21_03_10/all_moe2.csv.gz
    script: rels.mr_eve_mr
    source: MR-EvE-2021-03-10
  
  mr-eve-gwas-variant:
    name: GWAS_TO_VARIANT
    files:
      1: mr-eve/21_03_10/all_inst.csv.gz
    script: rels.gwas_to_variant
    source: MR-EvE-2021-03-10

  semmed-subject-term:
    name: SEMMEDDB_SUB
    files:
      1: semmeddb/semmedVER43_2021_R_PREDICATION_filter.csv.gz
    script: rels.semmed_subject_to_term
    source: SemMedDB_VER43_2021_R

  semmed-object-term:
    name: SEMMEDDB_OBJ
    files:
      1: semmeddb/semmedVER43_2021_R_PREDICATION_filter.csv.gz
    script: rels.semmed_object_to_term
    source: SemMedDB_VER43_2021_R

  semmed-literature:
    name: SEMMEDDB_TO_LIT
    files:
      1: semmeddb/semmedVER43_2021_R_PREDICATION_filter.csv.gz
    script: rels.semmed_to_literature
    source: SemMedDB_VER43_2021_R

  semmed-predicate:
    name: SEMMEDDB_PREDICATE
    files:
      1: semmeddb/semmedVER43_2021_R_PREDICATION_filter.csv.gz
    script: rels.semmed_predicate
    source: SemMedDB_VER43_2021_R    

  melodi-triple:
    name: GWAS_TO_LITERATURE_TRIPLE
    files:
      1: melodi/gwas-melodi-enrich-2021-05-21.tsv.gz
    script: rels.melodi-triple
    source: MELODI-Presto-2021-05-21  

  melodi-lit:
    name: GWAS_TO_LITERATURE
    files:
      1: melodi/gwas-melodi-enrich-2021-05-21.tsv.gz
    script: rels.melodi-lit
    source: MELODI-Presto-2021-05-21

  gwas-nlp:
    name: GWAS_NLP
    files:
      1: trait-nlp/ieu-gwas-cosine-20210504-0.tsv.gz
    script: rels.gwas-nlp
    source: Vectology-2021-05-04  
    
  ot-drug-disease:
    name: OPENTARGETS_DRUG_TO_DISEASE
    files:
      1: opentargets/open_targets_2021-05-13.csv
    script: rels.opentargets_drug_disease
    source: Opentargets-21.04

  cpic-drug-gene:
    name: CPIC
    files:
      1: CPIC/cpicPairs-2021-05-04.csv
    script: rels.cpic_gene_drug
    source: CPIC-2021-05-04

  tissue-gene-gtex:
    name: EXPRESSED_IN
    files:
      1: gtex/GTEx_Analysis_2016-01-15_v7_RNASeQCv1.1.8_gene_median_tpm.gct.gz
    script: rels.tissue-gene-gtex
    source: GTEx-2016-01-15_v7_RNASeQCv1.1.8

  protein-protein-string:
    name: STRING_INTERACT_WITH
    files:
      1: string-db/9606.protein.links.v11.0.txt.gz
      2: string-db/human.uniprot_2_string.2018.tsv.gz
    script: rels.protein_protein_string
    source: STRING-v11

  bn-gwas-gencor:
    name: GEN_COR
    files:
      1: ben-neale/genetic_correlation_matrices/data-2020-12-02.csv
    script: rels.gwas-gencor
    source: http://www.nealelab.is/blog/2019/10/10/genetic-correlation-results-for-heritable-phenotypes-in-the-uk-biobank

  gwas-umls-metamap-lite:
    name: METAMAP_LITE
    files:
      1: metamap/metamap-data-2021-05-06.tsv
    script: rels.gwas-metamap
    source: MetaMapLite-2021-05-04

  gwas-prs:
    name: PRS
    files:
      1: tom-richardson-prs-atlas/5e05.txt
      2: tom-richardson-prs-atlas/gwas-ids.txt
    script: rels.gwas-prs
    source: PRS-ATLAS

  xqtl-single-snp-mr-snp-gene:
    name: XQTL_SINGLE_SNP_MR_SNP_GENE
    files:
      1: xqtl-processed/XQTL_SINGLE_SNP_MR_SNP_GENE.csv
    script: rels.xqtl-single-snp-mr-snp-gene
    source: xQTL

  xqtl-single-snp-mr-gene-gwas:
    name: XQTL_SINGLE_SNP_MR_GENE_GWAS
    files:
      1: xqtl-processed/XQTL_SINGLE_SNP_MR_GENE_GWAS.csv
    script: rels.xqtl-single-snp-mr-gene-gwas
    source: xQTL

  xqtl-multi-snp-mr:
    name: XQTL_MULTI_SNP_MR
    files:
      1: xqtl-processed/XQTL_MULTI_SNP_MR.csv
    script: rels.xqtl-multi-snp-mr
    source: xQTL

  efo-parent-child:
    name: EFO_CHILD_OF
    files:
      1: EFO/efo_edges_2021-05-04.csv
    script: rels.efo-parent-child
    source: 2021-04-20 EFO 3.29.1

  efo-gwas-nlp:
    name: GWAS_NLP_EFO
    files:
      1: EFO/gwas-vec-efo-ids-01-09-20.tsv
    script: rels.efo-gwas-nlp
    source: Vectology
    
  gwas-efo-ebi:
    name: GWAS_EFO_EBI
    files:
      1: ebigwas/ebi-gwas-efo-2021-05-04.tsv
    script: rels.ebi_gwas_efo
    source: EBI GWAS Catalog 2021-05-04

  medrxiv-subject-term:
    name: MEDRXIV_SUB
    files:
      1: semrep/medrxiv_2021-05-05_semrep_filter.csv.gz
    script: rels.medrxiv_subject_to_term
    source: medRxiv-2021-05-04

  medrxiv-object-term:
    name: MEDRXIV_OBJ
    files:
      1: semrep/medrxiv_2021-05-05_semrep_filter.csv.gz
    script: rels.medrxiv_object_to_term
    source: medRxiv-2021-05-04

  medrxiv-literature:
    name: MEDRXIV_TO_LIT
    files:
      1: semrep/medrxiv_2021-05-05_semrep_filter.csv.gz
    script: rels.medrxiv_to_literature
    source: medRxiv-2021-05-04

  medrxiv-predicate:
    name: MEDRXIV_PREDICATE
    files:
      1: semrep/medrxiv_2021-05-05_semrep_filter.csv.gz
    script: rels.medrxiv_predicate
    source: medRxiv-2021-05-04

  biorxiv-subject-term:
    name: BIORXIV_SUB
    files:
      1: semrep/biorxiv_2021-05-05_semrep_filter.csv.gz
    script: rels.biorxiv_subject_to_term
    source: bioRxiv-2021-05-04

  biorxiv-object-term:
    name: BIORXIV_OBJ
    files:
      1: semrep/biorxiv_2021-05-05_semrep_filter.csv.gz
    script: rels.biorxiv_object_to_term
    source: bioRxiv-2021-05-04

  biorxiv-literature:
    name: BIORXIV_TO_LIT
    files:
      1: semrep/biorxiv_2021-05-05_semrep_filter.csv.gz
    script: rels.biorxiv_to_literature
    source: bioRxiv-2021-05-04

  biorxiv-predicate:
    name: BIORXIV_PREDICATE
    files:
      1: semrep/biorxiv_2021-05-05_semrep_filter.csv.gz
    script: rels.biorxiv_predicate
    source: bioRxiv-2021-05-04

  reactome-protein-pathway:
    name: PROTEIN_IN_PATHWAY
    files:
      1: reactome/UniProt2Reactome_All_Levels_human_2021-05-04.csv
    script: rels.reactome_protein_pathway
    source: Reactome-2021-05-04
  
  reactome-pathway-pathway:
    name: PATHWAY_CHILD_OF
    files:
      1: reactome/ReactomePathwaysRelation_human_2021-05-04.csv
    script: rels.reactome_pathway_pathway
    source: Reactome-2021-05-04

  gene-clinvar-disease-mondo:
    name: GENE_TO_DISEASE
    files:
      1: clinvar/clinvar_gene_condition_source_id-2021-05-04_tidy_subset_MONDO.tsv
    script: rels.gene_clinvar_disease_mondo
    source: Clinvar-2021-05-04
