meta_nodes:
  # Drug:
  #   properties:
  #     id:
  #       type: string
  #     label:
  #       type: string
  #     molecule_type:
  #       type: string
  #   required:
  #     - label
  #     - id
  #   index: label
  #   meta:
  #     _id: id
  #     _name: label  
  Gene:
    properties:
      adme_gene:
        type: string
      biomart_source:
        type: string
      bio_druggable:
        type: string
      chr:
        type: string
      description:
        type: string
      druggability_tier:
        type: string
      end:
        type: integer
      ensembl_id:
        type: string
      name:
        type: string
      reactome_id:
        type: string
      small_mol_druggable:
        type: string
      start:
        type: integer
      type:
        type: string
    required:
      - ensembl_id
      - name
    index: ensembl_id
    meta:
      _id: ensembl_id
      _name: name  
  Gwas:
    properties:
      author:
        type: string
      build:
        type: string
      category:
        type: string
      consortium:
        type: string
      covariates:
        type: string
      coverage:
        type: string
      doi:
        type: string
      group_name:
        type: string
      id:
        type: string
      imputation_panel:
        type: string
      mr:
        type: string
      name:
        type: string
      ncase:
        type: string
      ncontrol:
        type: string
      note:
        type: string
      nsnp:
        type: string
      ontology:
        type: string
      pmid:
        type: string
      population:
        type: string
      sample_size:
        type: string
      sd:
        type: string
      sex:
        type: string
      study_design:
        type: string
      subcategory:
        type: string
      trait:
        type: string
      unit:
        type: string
      year:
        type: string
    required:
      - nsnp
      - trait
      - id
    index: id
    meta:
      _id: id
      _name: trait 
  Pathway:
    properties:
      url:
        type: string
      name:
        type: string
      id:
        type: string
    required:
      - name
      - id
    index: id
    meta:
      _id: id
      _name: name 
  Protein:
    properties:
      uniprot_id:
        type: string
      name:
        type: string
    required:
      - uniprot_id
      - name
    index: uniprot_id
    meta:
      _id: uniprot_id
      _name: name
  Variant:
    properties:
      id:
        type: string
      name:
        type: string
      pos:
        type: integer
      chr:
        type: string
      ref:
        type: string
      alt:
        type: string
      build:
        type: string    
    required:
      - id
      - name
    index: name
    meta:
      _id: id
      _name: name

meta_rels:
  GENE_TO_PROTEIN:
    properties:
      source:
        type: Gene
      target:
        type: Protein
    required:
      - source
      - target
  GWAS_TO_VARIANT:
    properties:
      source:
        type: Gwas
      target:
        type: Variant
      beta:
        type: float
      eaf:
        type: float
      ncase:
        type: integer
      ncontrol:
        type: integer
      pval:
        type: float
      samplesize:
        type: integer
      se:
        type: float
    required:
      - source
      - target
      - beta
      - pval
      - samplesize
  PATHWAY_CHILD_OF:
    properties:
      source:
        type: Pathway
      target:
        type: Pathway
    required:
      - source
      - target 
  PROTEIN_IN_PATHWAY:
    properties: 
      source:
        type: Protein
      target:
        type: Pathway
    required:
      - source
      - target 
  OPENGWAS_TOPHITS:
    properties:
      source:
        type: Gwas
      target:
        type: Variant
      beta:
        type: float
      pval:
        type: float
    required:
      - source
      - target 
      - beta
      - pval
  # OPENTARGETS_DRUG_TO_TARGET:
  #   properties:
  #     source:
  #       type: Drug
  #     target:
  #       type: Gene
  #     action_type:
  #       type: string
  #     phase:
  #       type: string
  #   required:
  #     - source
  #     - target 
  #     - phase
  #     - action_type
  VARIANT_TO_GENE:
    properties:
      source:
        type: Variant
      target:
        type: Gene
      allele:
        type: string
      amino_acids:
        type: string
      cdna_position:
        type: string
      cds_position:
        type: string
      codons:
        type: string
      consequence:
        type: string
      existing_variation:
        type: string
      extra:
        type: string
      feature:
        type: string
      feature_type:
        type: string
      location:
        type: string
      protein_position:
        type: string
    required:
      - source
      - target 
      - location
      - allele
      - feature
      - feature_type
      - consequence
      - cdna_position
      - cds_position
      - protein_position
      - amino_acids
      - codons
      - existing_variation
      - extra